name: AWS SSM Send Command
description: "Send a command to an EC2 instance using AWS SSM"
inputs:
  aws-region:
    required: true
    description: "The AWS region"
  instance-id:
    required: true
    description: "The instance ID"
  document-name:
    required: true
    description: "The name of the SSM document"
  command:
    required: true
    description: "The command to send"
  wait_attempts:
    required: false
    description: "The number of attempts to wait for the command to be executed"
    default: "10"
outputs:
  command-id:
    description: "The ID of the command"
    value: ${{ fromJson(steps.aws-ssm-send-command.outputs.invocation).Command.CommandId }}
  result:
    description: "The result of the command"
    value: ${{ steps.aws-ssm-get-command-invocation.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: commands
      # Build the commands json array from the command input
      shell: bash
      run: |
        echo -n "json=" >> $GITHUB_OUTPUT
        cat <<'EOF' | jq -R -c '[.]' >> $GITHUB_OUTPUT
        ${{ inputs.command }}
        EOF

    - id: aws-ssm-send-command
      shell: bash
      run: |
        invocation=$(aws ssm send-command \
          --instance-ids "${{ inputs.instance-id }}" \
          --document-name "${{ inputs.document-name }}" \
          --parameters "commands=$(echo '${{ steps.commands.outputs.json }}')" \
          --output json)
         echo "invocation=$(echo $invocation | jq -c .)" >> $GITHUB_OUTPUT

    - id: aws-ssm-wait-command-executed
      continue-on-error: true
      shell: bash --noprofile --norc -o pipefail {0}
      run: |
        for attempt in $(seq 1 ${{ inputs.wait_attempts }}); do

          aws ssm wait command-executed --command-id ${{ fromJson(steps.aws-ssm-send-command.outputs.invocation).Command.CommandId }} --instance-id "${{ inputs.instance-id }}"
          exit_code=$?

          if [ $exit_code -ne 0 ]; then
            echo "Error: $exit_code"

            if [ $attempt -eq ${{ inputs.wait_attempts }} ]; then
              exit $exit_code
            fi

            status=$(aws ssm get-command-invocation \
              --instance-id "${{ inputs.instance-id }}" \
              --command-id ${{ fromJson(steps.aws-ssm-send-command.outputs.invocation).Command.CommandId }} \
              --output json | jq -r '.Status')
            echo "Status: $status"

            if [ "$status" == "InProgress"  ] || [ "$status" == "Pending" ] || [ "$status" == "Delayed" ]; then
              echo "Retrying in 10 seconds..."
              sleep 10
              echo
              echo "Attempt $(($attempt + 1)) of ${{ inputs.wait_attempts }}"
            else
              exit 0
            fi
          fi
        done

    - id: aws-ssm-get-command-invocation
      shell: bash
      run: |
        result=$(aws ssm get-command-invocation \
          --instance-id "${{ inputs.instance-id }}" \
          --command-id ${{ fromJson(steps.aws-ssm-send-command.outputs.invocation).Command.CommandId }} \
          --output json)
        echo "result=$(echo "$result" | jq -c .)" >> $GITHUB_OUTPUT
        echo "$result" | jq -r '.StandardOutputContent'
        echo "$result" | jq -r '.StandardErrorContent' >&2
        exit $(echo "$result" | jq -r '.ResponseCode')
